# Generated by Django 4.2.5 on 2023-10-06 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('part_number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('purchase_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('department_name', models.CharField(max_length=20)),
                ('hod_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_serial_number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('life', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchase_order_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('purchase_order_date', models.DateField()),
                ('supplier', models.CharField(max_length=20)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('lab_name', models.CharField(max_length=10)),
                ('lab_incharge', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('department_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.department')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('purchase_date', models.DateField()),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('purchase_order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('not_working_quantity', models.PositiveIntegerField()),
                ('remarks', models.TextField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.equipment')),
                ('lab_incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(max_length=100)),
                ('number_of_equipments', models.PositiveIntegerField()),
                ('details', models.TextField()),
                ('lab_incharge', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='invoice_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.invoice'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='lab_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab'),
        ),
        migrations.CreateModel(
            name='ConsumableStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField()),
                ('lead', models.PositiveIntegerField()),
                ('lag', models.PositiveIntegerField()),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.consumable')),
            ],
        ),
        migrations.AddField(
            model_name='consumable',
            name='invoice_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.invoice'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='lab_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab'),
        ),
    ]
