# Generated by Django 3.2.18 on 2023-10-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='lab_number',
            new_name='lab',
        ),
    ]
