# Generated by Django 3.2.18 on 2023-10-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_rename_lab_number_equipment_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='hod_name',
            field=models.CharField(max_length=30),
        ),
    ]
