# Generated by Django 4.2.5 on 2023-10-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0003_auto_20231009_1458"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consumable",
            old_name="purchase_quantity",
            new_name="distributed_quantity",
        ),
    ]
