# Generated by Django 4.2.5 on 2023-10-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0004_rename_purchase_quantity_consumable_distributed_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="lab",
            new_name="lab_number",
        ),
        migrations.AlterField(
            model_name="department",
            name="department_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="department",
            name="hod_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="equipmentissue",
            name="details",
            field=models.TextField(),
        ),
    ]
