# Generated by Django 3.2.18 on 2023-10-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_rename_lab_equipment_lab_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='residual_value',
            field=models.IntegerField(default=0),
        ),
    ]
