# Generated by Django 3.2.18 on 2023-10-12 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_equipment_residual_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('experiment_number', models.CharField(max_length=255)),
                ('experiment_name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipmentissue',
            name='experiment',
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Apparatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparatus_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('experiment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.experiment')),
            ],
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='experiment_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lab.experiment'),
            preserve_default=False,
        ),
    ]
